### ISSUE TITLE
RDB Persistence - handle "Stage 1 doesn't create file" confusion

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-redis#111]
> rdb persistence stage 1(read config from arg) doesn't create corresponding rdb file, is it intended?
> In stage 2 I implemented the server to crash when there's no rdb file but the argument is supplied.
> I was figuring out why I was getting os error 2(no file) error for a while and I realized the test was failing at stage 1, not 2.

The tester is "right" here in the sense that if a file doesn't exist, the program must write it when a flush occurs. 

We have two options here: 

- (a) Keep existing tester behaviour, and add a comment noting this
- (b) Just create an empty .rdb file, so that users don't have to deal with this

(a) is a more "true" implementation, (b) is less confusing but still lets people deal with `.rdb` files and learn about them.

**Comment by rcardenes** [comment]
A compromise: just mention the expected behavior in the instructions?

**Comment by rohitpaulk** [comment]
@rcardenes yep, works! That's what I meant by option (a) btw - that we'd update the instructions to highlight this behaviour. 

Fixed in https://github.com/codecrafters-io/build-your-own-redis/pull/113!
