### ISSUE TITLE
Improve anti-cheat message

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-redis#126]
This applies to all challenges - When an anti-cheat stage fails, we must say "Please contact hello@codecrafters.io if you think this is an error"

> remote: anti-cheat (ac1) failed.
> remote: Are you sure you aren't running this against the actual Redis?

**Comment by rohitpaulk** [comment]
I'll add more details here soon - we should also replace the "Are you sure ..." message

**Comment by rohitpaulk** [comment]
```
remote: anti-cheat (ac1) failed.
remote: Please contact us at hello@codecrafters.io if you think is a mistake
```

**Comment by ryan-gang** [comment]
Updated this here: https://github.com/codecrafters-io/redis-tester/pull/133
