### ISSUE TITLE
Improve error message for message length mismatch

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-redis#131]
![Screenshot_2024-02-22_at_10 20 31_PM](https://github.com/codecrafters-io/build-your-own-redis/assets/3893573/5e48fa4a-d8ae-46f6-ab4f-5c4fb40065bb)

Instead of just saying "Length mismatch", let's say: 

```
Expected 28 bytes, received 24 bytes
Expected: ....
Received: ... 
```

We might also be able to re-use https://github.com/codecrafters-io/tester-utils/blob/master/bytes_diff_visualizer/bytes_diff_visualizer.go in some way, but probably not needed here since there's no non-ascii characters involved

**Comment by rohitpaulk** [comment]
Thanks to @b14cknc0d3 for reporting this!

**Comment by rohitpaulk** [comment]
If it turns out that we're reading **more** bytes than expected (and not less), then that's a separate bug - we might need to truncate our reads so that we don't read more than what we're trying to assert.

**Comment by ryan-gang** [comment]
Should be fixed.
