### ISSUE TITLE
Account for processing delay in replication / command processing stage

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-redis#132]
> Im having trouble with syncronization in replication command processing

> I have one thread that is listening for commands (like the sets) from the master, and another that is listening for commands sent directly to my replica

> Sometimes the get from the test comes before I can process the set from the master. What is the recommended approach to syncronize that?

> ![image](https://github.com/codecrafters-io/build-your-own-redis/assets/3893573/fba645ad-3b0c-4507-9422-afa129f3e948)

> You can see I get the first SET, then I get both GETs, and only then I get the rest of the SETs 

I think we need to be either sleeping for a bit before running the `GET` commands, or we should retry them for a certain time period. The user's implementation seems correct from a practical perspective, it's expected that there might be a small delay between a command being propagated and it being applied on the client.

**Comment by rohitpaulk** [comment]
Thanks to @urielsalis for highlighting this!

**Comment by rohitpaulk** [comment]
Let's implement retries instead of an arbitrary sleep (that way tests are fast for most cases). If the GET command returns null the first time, let's sleep for 500ms and retry again, upto 5 times per key.

**Comment by rohitpaulk** [comment]
https://github.com/codecrafters-io/redis-tester/pull/92

**Comment by ryan-gang** [comment]
Fixed by: https://github.com/codecrafters-io/redis-tester/pull/92.
