### ISSUE TITLE
Improve error logs for INFO replication stage

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-redis#134]
<img width="1116" alt="Screenshot 2024-02-27 at 09 58 59" src="https://github.com/codecrafters-io/build-your-own-redis/assets/3893573/f3d38e32-833d-405a-b01d-49944b036f59">

Let's see if we can include the received response somewhere?

Thanks to @lipinskipawel for pointing this out!

**Comment by lipinskipawel** [comment]
I have included additional byte logging
![image](https://github.com/codecrafters-io/build-your-own-redis/assets/47224674/4cf3c3f8-3f75-4eda-be25-3fcf1dd03902)
Last bytes looks good. 58, 48, 13, 10 https://www.ascii-code.com/

**Comment by rohitpaulk** [comment]
This is now being logged! 

<img width="714" alt="Screenshot 2024-04-17 at 13 47 32" src="https://github.com/codecrafters-io/build-your-own-redis/assets/3893573/a5a236ee-4be9-48b0-bef6-ad82ef461075">
