### ISSUE TITLE
Multiple replicas stage - all replicas advertise the same "listening" port

### ISSUE THREAD

**Issue by rohitpaulk** [codecrafters-io/build-your-own-redis#153]
<img width="744" alt="Screenshot 2024-03-25 at 22 08 24" src="https://github.com/codecrafters-io/build-your-own-redis/assets/3893573/bd500062-e00c-41df-97ed-2273305bc754">

Although this shouldn't affect test results, it can certainly cause confusion. Let's have all of these use different ports in their `REPLCONF` commands.

**Comment by rohitpaulk** [comment]
Thanks to @Eredom for reporting this!

**Comment by ryan-gang** [comment]
Fixed by https://github.com/codecrafters-io/redis-tester/pull/135
