### ISSUE TITLE
gleam run doesn't take source file as an input 

### ISSUE THREAD

**Issue by Juhan280** [codecrafters-io/build-your-own-redis#170]
[https://github.com/codecrafters-io/build-your-own-redis/blob/6f863efccc475868b1bc529a70f2552f8e3c48e5/starter_templates/gleam/spawn_redis_server.sh#L8](https://github.com/codecrafters-io/build-your-own-redis/blob/6f863efccc475868b1bc529a70f2552f8e3c48e5/starter_templates/gleam/spawn_redis_server.sh#L8)

Here `src/redis.gleam` doesn't do anything other than just passing it to the argv

This should work just fine

```sh
exec gleam run -- "$@"
```

**Comment by rohitpaulk** [comment]
Fixed in https://github.com/codecrafters-io/build-your-own-redis/pull/171!
