### ISSUE TITLE
Add support for rust 1.80.

### ISSUE THREAD

**Issue by ubiquitousbyte** [codecrafters-io/build-your-own-redis#270]
I am implementing the RESP protocol and I am using an API in the Rust standard library that has only been stabilised in the 1.80 series. That API is the `split_at_checked` function defined on byte slices. Currently, my implementation cannot be compiled on the CodeCrafters platform. This can be fixed by bumping the supported Rust version to 1.80.

**Comment by rohitpaulk** [comment]
Yep, we’ll get this upgrade done next week! I’ll try to get Redis upgraded for you today.

**Comment by andy1li** [comment]
Closed by https://github.com/codecrafters-io/build-your-own-redis/pull/271
